### ISSUE TITLE
Does not work with node 7 and npm 4

### ISSUE THREAD

**Issue by dotboris** [Olical/bastion#7]
I've tried setting up a project with bastion and could not get it to work. I was getting some strange errors regarding `babel-core` being missing and failing to find files in `node_modules/bastion/node_modules/...`.

I have managed to reproduce this issue with the babel-example project.

Note that I'm running node v7.3.0 and npm 4.0.5:

```sh
$ node --version
v7.3.0
$ npm --version
4.0.5
```

I first tried to clone the example repo and build, but that failed:

```sh
$ npm i
... a ton of output ...
$ make build
# Bundles src/index.js into dist/bundle.js
# Essentially a production build.
# Performs all checks
BASTION_LOG_LEVEL=silly ./node_modules/.bin/bastion
2017-01-06T02:40:43.121Z - verbose: found config file bastion.conf.js
2017-01-06T02:40:43.127Z - verbose: entry: ./src/entry
2017-01-06T02:40:43.128Z - verbose: bundle: ./dist/bundle.js
2017-01-06T02:40:43.190Z - verbose: Hash: 4aea322a370b7a874b39
Version: webpack 1.14.0
Time: 41ms
          Asset     Size  Chunks             Chunk Names
bastion.conf.js  1.55 kB       0  [emitted]  main
chunk    {0} bastion.conf.js (main) 28 bytes [rendered]
    [0] multi main 28 bytes {0} [built] [1 error]

ERROR in Cannot find module 'babel-core'
 @ multi main
2017-01-06T02:40:43.191Z - verbose: compiled config file of length 1553
(node:13511) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module "/home/dotboris/code/science/bastion-example/bastion.conf.js"
(node:13511) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looks like `babel-core` was not present. I think this has to do with the fact that it's a peer dependency in `babel-loader` and that it's not being loaded by default in newer versions of npm.

I tried installing `babel-core` and building again, but it still didn't work.

```sh
$ npm i --save-dev babel-core
bastion-example@1.0.0 /home/dotboris/code/science/bastion-example
└─┬ babel-core@6.21.0
  ├─┬ babel-generator@6.21.0
  │ ├─┬ detect-indent@4.0.0
  │ │ └─┬ repeating@2.0.1
  │ │   └── is-finite@1.0.2
  │ └── jsesc@1.3.0
  ├── babel-helpers@6.16.0
  ├─┬ babel-register@6.18.0
  │ ├── home-or-tmp@2.0.0
  │ └── source-map-support@0.4.8
  ├── convert-source-map@1.3.0
  └── slash@1.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN bastion-example@1.0.0 No repository field.
$ make build
# Bundles src/index.js into dist/bundle.js
# Essentially a production build.
# Performs all checks
BASTION_LOG_LEVEL=silly ./node_modules/.bin/bastion
2017-01-06T02:41:29.697Z - verbose: found config file bastion.conf.js
2017-01-06T02:41:29.703Z - verbose: entry: ./src/entry
2017-01-06T02:41:29.704Z - verbose: bundle: ./dist/bundle.js
2017-01-06T02:41:29.956Z - verbose: Hash: 4aea322a370b7a874b39
Version: webpack 1.14.0
Time: 229ms
          Asset     Size  Chunks             Chunk Names
bastion.conf.js  1.55 kB       0  [emitted]  main
chunk    {0} bastion.conf.js (main) 28 bytes [rendered]
    [0] multi main 28 bytes {0} [built] [1 error]

ERROR in ./bastion.conf.js
Module build failed: ReferenceError: Unknown plugin "/home/dotboris/code/science/bastion-example/node_modules/bastion/node_modules/babel-plugin-transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/dotboris/code/science/bastion-example"
    at /home/dotboris/code/science/bastion-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/dotboris/code/science/bastion-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/dotboris/code/science/bastion-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/home/dotboris/code/science/bastion-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/dotboris/code/science/bastion-example/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/dotboris/code/science/bastion-example/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/dotboris/code/science/bastion-example/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/dotboris/code/science/bastion-example/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/home/dotboris/code/science/bastion-example/node_modules/babel-loader/lib/index.js:133:12)
 @ multi main
2017-01-06T02:41:29.956Z - verbose: compiled config file of length 1553
(node:13563) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module "/home/dotboris/code/science/bastion-example/bastion.conf.js"
(node:13563) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looks like some module is looking for modules under the `node_modules/bastion/node_modules/` dir. This fails because newer version of npm >= 3 installs dependencies in a flat structure instead of a nested one. This leads to `node_modules/bastion/node_modules/` to be missing.

**Comment by Olical** [comment]
Yep, it would require some sort of dependency tree searching I presume. You could probably get by if you looked in `node_modules` then in `node_modules/bastion/node_modules` or something. But the thought of having conflicting versions gives me headaches.

I think a better approach to this sort of tool is what [create-elm-app](https://www.npmjs.com/package/create-elm-app) did. It's all self contained within `elm-app`, sure. But when you want to tweak it you can run a command that dumps all the webpack shenanigans into your current directory for you to edit.

I think create-react-app may do this too? Although I'm not sure.

I'm afraid I'm not planning on looking into this personally. I'm trying my best to work on things other than JavaScript so I'm adverse to maintaining things like this. I'm happy to facilitate pull requests, but overhauls are kind of out of the question for these projects of mine now.

Thank you for the excellent report, though, I'll leave this here on the off chance that I muster up the motivation to work on it or someone else does.
